version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: forum_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: