apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: blog-subscription
spec:
                    # fiks senere    
  # topic: orders
  # route: /orders-sub
  pubsubname: blogpubsub
scopes: 
